<?php
return [
    [
        'name' => 'Technology',
        'code' => 'technology',
        'type' => Rikkei\Tag\View\TagConst::FIELD_TYPE_TAG,
        'child' => [
            [
                'name' => 'Language', 
                'code' => 'language',
                'type' => Rikkei\Tag\View\TagConst::FIELD_TYPE_TAG,
                'tags' => [
                    'PHP',
                    'Python',
                    'Java',
                    'Objective-C',
                    'Swift',
                    'Javascript',
                    'Ruby',
                    'C',
                    'C++',
                    'C#',
                    'VB.NET',
                    'VB6',
                    'COBOL',
                    'Assembly',
                    'Perl',
                    'Shell',
                    'Groovy',
                    'Scala',
                    'CSS',
                    'HTML',
                    'HTML5',
                    'CSS3',
                    'Unity',
                    'Java Android',
                    'Kotlin',
                    'Dart',
                    'Electron JS',
                    'React Native',
                    'Flutter',
                    'ReactJS',
                    'Golang',
                ]
            ],
            [
                'name' => 'English', 
                'code' => 'english',
                'type' => Rikkei\Tag\View\TagConst::FIELD_TYPE_TAG,
                'tags' => [
                    'Listening',
                    'Comunication',
                ]
            ],
            [
                'name' => 'Framework', 
                'code' => 'framework',
                'type' => Rikkei\Tag\View\TagConst::FIELD_TYPE_TAG,
                'tags' => [
                    '.NET MVC',
                    'ASP.NET CORE',
                    'ASP.NET MVC',
                    'ASP.NET WINFORM',
                    'AWS lambda',
                    'Address',
                    'AndroidSDK',
                    'AngularJS',
                    'Appcelerator',
                    'BackBoneJS',
                    'Basic4Android',
                    'Bootstrap',
                    'CakePHP',
                    'Coco2d',
                    'Coco2d-x',
                    'Cocoa',
                    'Codeigniter',
                    'Core Framework',
                    'CoreUI',
                    'Corona SDK',
                    'Dojo Mobile',
                    'EC-Cube',
                    'Elasticsearch',
                    'Entity Framework',
                    'Espresso',
                    'Express.js',
                    'Facebook-ios-sdk',
                    'Framework7',
                    'Fuel',
                    'Hibernate',
                    'JQuery Mobile',
                    'JSF',
                    'JSONKit',
                    'Jquery',
                    'Kinetic',
                    'Kony',
                    'Laravel',
                    'Liferay',
                    'Lumen',
                    'MFC',
                    'MKStoreKit',
                    'Mainframe',
                    'MapKit',
                    'Marionette',
                    'Maven',
                    'Monaca',
                    'Mybatis',
                    'Nodejs',
                    'OpenCV',
                    'Phonegap',
                    'Pylon',
                    'QT',
                    'RactiveJS',
                    'Rails',
                    'Reachability',
                    'React',
                    'React native',
                    'Robolectric',
                    'Robotium',
                    'SafariService',
                    'Sencha Touch',
                    'Slim',
                    'Socket.IO',
                    'Spring',
                    'SpringMVC',
                    'Sproutcore',
                    'Struts',
                    'Struts2',
                    'Symfony',
                    'The .NET Compact Framework',
                    'TwitterKit',
                    'UWP',
                    'Unity',
                    'Vue',
                    'Vuejs',
                    'WCP',
                    'WPF',
                    'Wicket',
                    'WinForm',
                    'Xamarin',
                    'Xarmarin',
                    'Yii',
                    'Yii2',
                    'Zend',
                    'Salesforce',
                    'Alipay',
                    'Data Studio',
                    'NextJS',
                    'Ant Design',
                    'SharePoint Designer'
                ]
            ],
            [
                'name' => 'Library', 
                'code' => 'library',
                'type' => Rikkei\Tag\View\TagConst::FIELD_TYPE_TAG,
                'tags' => [
                    'ACRA',
                    'AChartEngine',
                    'AFNetworking',
                    'AORM',
                    'AVFoundation',
                    'AVSpeechSynthesizer',
                    'AboutLibraries',
                    'ActiveAndroid',
                    'AdvRecyclerView',
                    'Alamofire',
                    'Amcharts',
                    'AnUitor',
                    'Android Async HTTP',
                    'Android Bootstrap',
                    'Android Debug Database',
                    'Android Material Intro Screen',
                    'Android Satellite Menu',
                    'Android StackBlur',
                    'Android StepsView',
                    'Android Universal Image Loader',
                    'Android-Iconics',
                    'Android-ObservableScrollView',
                    'Android-Orma',
                    'Android-gpuimage',
                    'Android-image-filter',
                    'Android-parallax-recyclerview',
                    'Android-quick-response-code',
                    'Android-shape-imageview',
                    'AndroidAnnotations',
                    'AndroidCharts',
                    'AndroidGraphView',
                    'AndroidImageSlider',
                    'AndroidPhotoFilters',
                    'AndroidPlot',
                    'AndroidRTC',
                    'AndroidSlidingUpPanel',
                    'AndroidViewAnimations',
                    'ApnsPHP',
                    'Aquery',
                    'ArcMenu',
                    'Async Http Client',
                    'Async-expandable-list',
                    'AutoParcel',
                    'Aws-sdk',
                    'Aws-sdk-php-laravel',
                    'Axlsx',
                    'Barcodescanner',
                    'BetterPickers',
                    'BlurKit for Android',
                    'Bolts-iOS',
                    'Bootstrap',
                    'Bugfender',
                    'Butter Knife',
                    'ButterKnife',
                    'Bxslider',
                    'Calligraphy',
                    'CamView',
                    'Cancancan',
                    'Capistrano',
                    'Cardslib',
                    'Carrierwave',
                    'ChatJS',
                    'ChipsLayoutManager',
                    'Chuck',
                    'CircularFillableLoaders',
                    'ClosedXML.Excel',
                    'CommandDataBinding',
                    'Compass',
                    'Confetti',
                    'CoreAnimation',
                    'CoreBluetooth',
                    'CoreImage',
                    'CoreLocation',
                    'CropImage',
                    'Cropiwa',
                    'CrossSettings',
                    'Crystal Report',
                    'Crystal Reports',
                    'CsvHelper',
                    'Cupboard',
                    'DBFlow',
                    'Dagger',
                    'Dagger 2',
                    'Deployer',
                    'Devise',
                    'Dialogplus',
                    'DotNetZip',
                    'DraggablePanel',
                    'EasyDeviceInfo',
                    'EasyFonts',
                    'EasyListViewAdapters',
                    'EazeGraph',
                    'Elasticsearch',
                    'Epoxy',
                    'Espresso',
                    'EventBus',
                    'Excel Creator',
                    'FFImageLoading',
                    'Facebook SDK',
                    'FadingActionBar',
                    'Fast Android Networking',
                    'FastAdapter',
                    'FlexibleAdapter',
                    'FlipView',
                    'FloatingActionButton',
                    'Flotr2',
                    'Foursquare-CollectionPicker',
                    'Fresco',
                    'GPUImage',
                    'GPUImage for Android',
                    'Glide',
                    'Glide-transformations',
                    'Google API Client',
                    'Google Analytics',
                    'Google Map API',
                    'Grapecity (multirow, vv)',
                    'GraphHopper',
                    'Gravity View',
                    'GreedoLayout',
                    'GreenDAO',
                    'GridListViewAdapters',
                    'Grunt',
                    'Gson',
                    'Hawk',
                    'HelloCharts',
                    'HoloEverywhere',
                    'HoloGraphLibrary',
                    'Hugo',
                    'Hunalign',
                    'IcePick',
                    'Iconify',
                    'ImageCircle',
                    'ImageEffectFilter',
                    'Intervention Image',
                    'Ion',
                    'Isotope',
                    'ItemAnimators',
                    'JDXA',
                    'JQuery',
                    'JUnit',
                    'Jackson',
                    'Jasper',
                    'JavaFX',
                    'JazzyViewPager',
                    'Jinja2',
                    'Jsc3d',
                    'Json.Net',
                    'Jsoup',
                    'Jwt-auth',
                    'Kaminari',
                    'Konfetti',
                    'LeakCanary',
                    'Leonids',
                    'Less',
                    'ListViewAnimations',
                    'Log4Net',
                    'Log4j',
                    'Logger',
                    'LoggingInterceptor',
                    'Loopj',
                    'MBProgressHUD',
                    'MPAndroidChart',
                    'Material-SearchView',
                    'MaterialDrawer',
                    'Mobile Detect',
                    'Modernizr',
                    'Moment',
                    'Moment.php',
                    'Mp4parser',
                    'MultiRow for Windows Forms',
                    'NGUI',
                    'NPOI',
                    'NetOffice',
                    'NexusData',
                    'NexusDialog',
                    'NineOldAndroids',
                    'OAuthLibGithub',
                    'ORMLite',
                    'OkHttp',
                    'OmegaT',
                    'OpenCV',
                    'OpenXMLSDK',
                    'PHPExcel',
                    'PHPMailer',
                    'POI',
                    'Paginated Table',
                    'Paperclip',
                    'ParallaxHeaderViewPager',
                    'ParallaxPager',
                    'ParallaxPagerTransformer',
                    'Parceler',
                    'Parse',
                    'Passenger',
                    'PdfBox',
                    'Pdfkit',
                    'PersistentSearchBar',
                    'PhotoView',
                    'Phpmyadmin',
                    'Picasso',
                    'Picasso-transformations',
                    'PinnedList-Android',
                    'PinnedListView',
                    'PlusPak for Windows Forms',
                    'Poetry',
                    'Primefaces',
                    'Priority Job Queue',
                    'PrivacyStreams',
                    'ProgressWheel',
                    'PullToRefresh-ListView',
                    'Puma',
                    'QuickReturn',
                    'RabbitMQ',
                    'Rails_admin',
                    'Realm',
                    'Rebound',
                    'RecyclerViewBinding',
                    'RecyclerViewHelper',
                    'Redactor',
                    'Report Viewer',
                    'Retrofit',
                    'Retrolambda',
                    'RoboGuice',
                    'Robolectric',
                    'RoundedImageView',
                    'Rubocop',
                    'RushOrm',
                    'RxAndroid',
                    'RxCache',
                    'RxJava',
                    'SDWebImage',
                    'SQLAlchemy',
                    'SQLBrite',
                    'SVProgressHUD',
                    'SVPullToRefresh',
                    'Sass',
                    'Schematic',
                    'Scissors',
                    'Scrollable',
                    'Seagate crystal report',
                    'Sensey',
                    'ShowcaseView',
                    'Sidekiq',
                    'SimpleRatingBar',
                    'SlidingMenu',
                    'SmoothProgressBar',
                    'Social',
                    'SocketRocket',
                    'SortableTableView',
                    'SparkButton',
                    'Spork',
                    'SpritePacker',
                    'Stetho',
                    'Sticky-headers-recyclerview',
                    'StickyListHeaders',
                    'StorIO',
                    'SugarORM',
                    'Tape',
                    'ThymeLeaf',
                    'Timber',
                    'Toasty',
                    'Twitter Fabric',
                    'UGUI',
                    'UltimateRecyclerView',
                    'Unet',
                    'Unit Test on visual studio',
                    'Universal Image Loader',
                    'User32.dll',
                    'UserDialogs',
                    'VBA',
                    'VidEffects',
                    'Volley',
                    'Vuforia',
                    'WebRTC',
                    'Websocket-rails',
                    'WilliamChart',
                    'WindowsBase',
                    'ZXing',
                    'ZXing Android Embedded'
                ]
            ],
            [
                'name' => 'OS', 
                'code' => 'os',
                'type' => Rikkei\Tag\View\TagConst::FIELD_TYPE_TAG,
                'tags' => [
                    'Cent OS',
                    'Fedora',
                    'iOS',
                    'Linux',
                    'Mac OS',
                    'RedHat',
                    'Ubuntu',
                    'Win CE',
                    'Windows',
                    'Windows Server'
                ]
            ],
            [
                'name' => 'IDE', 
                'code' => 'ide',
                'type' => Rikkei\Tag\View\TagConst::FIELD_TYPE_TAG,
                'tags' => [
                    'AIDE',
                    'Android Studio',
                    'CLion',
                    'CocoaPod',
                    'Code::Block',
                    'Dev-C++',
                    'Eclipse',
                    'Git',
                    'IDEA',
                    'IntelliJ IDEA',
                    'Java Editor',
                    'Jetbrains Rider',
                    'Microsoft Excel',
                    'Mono',
                    'NetBeans',
                    'PHPStorm',
                    'Rubymine',
                    'Sublime Text',
                    'Visual Basic Tools',
                    'Visual Studio',
                    'Visual code',
                    'Webstorm',
                    'XCode',
                    'Xamarin Studio'
                ]
            ],
            [
                'name' => 'Database', 
                'code' => 'database',
                'type' => Rikkei\Tag\View\TagConst::FIELD_TYPE_TAG,
                'tags' => [
                    'AWS Dynamo DB',
                    'Aurora 5.6.10a',
                    'CoreData',
                    'DB2',
                    'DBflute',
                    'Dynamodb',
                    'Groonga',
                    'MongoDB',
                    'MySQL',
                    'NSUserDefault',
                    'Oracle',
                    'PostgreSQL',
                    'Realm',
                    'SQL server',
                    'SQLite',
                    'SharedPreferences',
                    'SnappyDB',
                    'UserDefault'
                ]
            ],
            [
                'name' => 'Keyword',
                'code' => 'tech_keyword',
                'type' => Rikkei\Tag\View\TagConst::FIELD_TYPE_TAG,
                'tags' => [
                    '3D',
                    'AR',
                    'AWS',
                    'Android Auto',
                    'Android TV',
                    'Android Things',
                    'Android Wear',
                    'Audio call',
                    'Augmented reality',
                    'BLE',
                    'Beacons',
                    'CI',
                    'CMS',
                    'Cloud',
                    'Computer telephony integration(CTI)',
                    'Core location',
                    'Cross platform app',
                    'Drone',
                    'DynamoDB',
                    'EBL',
                    'EC site',
                    'EC2',
                    'Face detect',
                    'Face detection',
                    'Face tracking',
                    'Fulltext search',
                    'GPS',
                    'Google Fit',
                    'Google Maps',
                    'Google Places',
                    'Google VR',
                    'Gpu image',
                    'Image filter',
                    'Image processing',
                    'Lambda',
                    'Memcached',
                    'Microservices',
                    'RDS',
                    'Redis',
                    'Route 53',
                    'S3',
                    'Socket programming',
                    'Text recognization',
                    'Text to speech',
                    'Video Call',
                    'Video Streaming',
                    'Video processing',
                    'WebRTC',
                    'Websocket'
                ]
            ],
            [
                'name' => 'SDK', 
                'code' => 'sdk',
                'type' => Rikkei\Tag\View\TagConst::FIELD_TYPE_TAG,
                'tags' => [
                    'AWS SDK',
                    'Android SDK',
                    'Android support design',
                    'Facebook SDK',
                    'FirebaseSDK',
                    'Google SDKs',
                    'Google analytics',
                    'Google firebase',
                    'Google play service'
                ]
            ],
        ]
    ],
    [
        'name' => 'Domain',
        'code' => 'domain',
        'type' => Rikkei\Tag\View\TagConst::FIELD_TYPE_TAG,
        'child' => [
            [
                'name' => 'Domain chính', 
                'code' => 'domain_main',
                'type' => Rikkei\Tag\View\TagConst::FIELD_TYPE_TAG,
                'tags' => [
                    'Bảo hiểm',
                    'Chứng khoán',
                    'Du lịch',
                    'Dịch thuật',
                    'Entertainment',
                    'Game',
                    'Giáo dục',
                    'Hệ thống thông tin',
                    'Kế toán',
                    'Ngân hàng',
                    'Nhân sự',
                    'Quản lý tài sản',
                    'Social',
                    'Sản xuất',
                    'Thương mại điện tử',
                    'Thời trang',
                    'Tin tức',
                    'Tool',
                    'Trò chơi',
                    'Vận tải',
                    'Y tế'
                ]
            ],
            [
                'name' => 'Domain con', 
                'code' => 'domain_child',
                'type' => Rikkei\Tag\View\TagConst::FIELD_TYPE_TAG,
                'tags' => [
                    'Ads block content',
                    'Alarm',
                    'Ap du lịch',
                    'Automation test',
                    'Backup data',
                    'Blog',
                    'Bệnh viện',
                    'Caculator',
                    'Camera security',
                    'Card',
                    'Cloud integration',
                    'Contact',
                    'Container',
                    'Defense',
                    'Download accelerator',
                    'Dịch sách it',
                    'English',
                    'Filter thông tin sản phẩm',
                    'Horoscopes',
                    'Hệ quản trị nội dung',
                    'Hệ thống dịch tự động',
                    'Image',
                    'Japanese',
                    'Kế toán doanh nghiệp',
                    'Kết nối việc làm',
                    'Match 3',
                    'Music',
                    'Nhà trẻ',
                    'Piano+',
                    'Quiz',
                    'Quizgame cho training',
                    'Quản lý hội viên',
                    'Quản lý kho hàng',
                    'Quản lý đại học',
                    'Recipe',
                    'So sánh bằng sáng chế',
                    'Thanh toán online',
                    'Theo dõi sk',
                    'Thiết bị y tế',
                    'Tin tức trả phí',
                    'Tổng hợp thói quen người dùng',
                    'Video',
                    'Weather',
                    'Xử lý ảnh',
                    'Đầu tư tín thác',
                    'Đặt hàng online nhà sản xuất',
                    'Đặt hàng online thương mại'
                ]
            ],
            [
                'name' => 'Keyword', 
                'code' => 'domain_keyword',
                'type' => Rikkei\Tag\View\TagConst::FIELD_TYPE_TAG,
                'tags' => [
                    'GPS情報',
                    'SDカード',
                    'auかんたん決済',
                    'httpリクエスト',
                    'rtp over http',
                    'sms',
                    'spモート決済',
                    'wifi',
                    'お知らせ',
                    'アップロードクラウド',
                    'アプリケーションデータ',
                    'インタフェース',
                    'インベントリー',
                    'オプション',
                    'カテゴリー',
                    'カレンダー',
                    'クリニーク',
                    'クレジット',
                    'コンテナ',
                    'コンテンツプロバイダ',
                    'サウンドエンジン',
                    'シェア',
                    'ジャンル',
                    'ストリーミング',
                    'ストレージ',
                    'セキュリティゲート',
                    'ダウンロード',
                    'デビット',
                    'デポ',
                    'データベース',
                    'ドック',
                    'ネットワーク処理',
                    'ピッチ',
                    'ファイルmidi',
                    'ファイル処理',
                    'ファンド',
                    'フィルタ',
                    'ブックマーク',
                    'プレー',
                    'プレート',
                    'プレーヤー',
                    'マイナーバージョン',
                    'ヤード',
                    'ライセンスカウント',
                    'ライブストリーム',
                    'リスト',
                    'レシピ',
                    'ログアウト',
                    'ログイン',
                    'ローン',
                    '主契約',
                    '五線紙',
                    '休止',
                    '会員',
                    '会計',
                    '住宅ローン',
                    '保全',
                    '保険会社',
                    '保険料',
                    '保険者',
                    '保険金',
                    '健康診断',
                    '元本',
                    '先物',
                    '入庫',
                    '入金',
                    '入院',
                    '公式',
                    '公社債投資信託',
                    '円安',
                    '円高',
                    '処理',
                    '出庫',
                    '出金',
                    '分配金',
                    '動画広告',
                    '医療保障保険',
                    '医者',
                    '友達追加',
                    '収納',
                    '受取人',
                    '受注番号',
                    '受渡',
                    '口座',
                    '和音',
                    '器械',
                    '団体保険',
                    '在庫',
                    '外国為替相場',
                    '外貨預金',
                    '契約',
                    '契約者',
                    '患者',
                    '情報',
                    '投資',
                    '投資信託',
                    '振り込み',
                    '振替',
                    '接触',
                    '損益',
                    '新しいフィード',
                    '暗号化',
                    '暗証番号',
                    '月経',
                    '来院',
                    '株式',
                    '棚卸',
                    '検索連絡先',
                    '港',
                    '満期',
                    '源泉分離課税',
                    '為替予約',
                    '特約',
                    '生命保険',
                    '画像広告',
                    '税額控除',
                    '積立',
                    '管理台帳',
                    '糸',
                    '約定',
                    '給付金',
                    '総合課税',
                    '繰り上げ返済',
                    '航海番号',
                    '船',
                    '船会社',
                    '荷送人',
                    '著者',
                    '観光地',
                    '記事投稿',
                    '警報',
                    '財形制度',
                    '貯金',
                    '質権',
                    '退会',
                    '退院',
                    '通関検査',
                    '配当',
                    '重複した連絡先',
                    '金利',
                    '銘柄',
                    '除外キーワード',
                    '除外候補',
                    '預金'
                ]
            ],
        ]
    ],
    [
        'name' => 'Info',
        'code' => 'info',
        'type' => Rikkei\Tag\View\TagConst::FIELD_TYPE_INFO,
        'child' => [
            [
                'name' => 'Basic',
                'code' => 'info_basic',
                'type' => Rikkei\Tag\View\TagConst::FIELD_TYPE_INFO,
                'child' => [            
                    [
                        'name' => 'Division liên quan', 
                        'code' => 'division',
                        'type' => Rikkei\Tag\View\TagConst::FIELD_TYPE_INFO

                    ],
                    [
                        'name' => 'Tên PM',
                        'code' => 'pm',
                        'type' => Rikkei\Tag\View\TagConst::FIELD_TYPE_INFO
                    ],
                    [

                        'name' => 'Project type',
                        'code' => 'project_type',
                        'type' => Rikkei\Tag\View\TagConst::FIELD_TYPE_INFO
                    ],
                    [
                        'name' => 'Billable effort',
                        'code' => 'billable',
                        'type' => Rikkei\Tag\View\TagConst::FIELD_TYPE_INFO
                    ],
                    [
                        'name' => 'Plan effort',
                        'code' => 'plan_effort',
                        'type' => Rikkei\Tag\View\TagConst::FIELD_TYPE_INFO
                    ],
                    [
                        'name' => 'start date',
                        'code' => 'start_date',
                        'type' => Rikkei\Tag\View\TagConst::FIELD_TYPE_INFO
                    ],
                    [
                        'name' => 'end date',
                        'code' => 'end_date',
                        'type' => Rikkei\Tag\View\TagConst::FIELD_TYPE_INFO
                    ],
                    [
                        'name' => 'sales phụ trách',
                        'code' => 'sales',
                        'type' => Rikkei\Tag\View\TagConst::FIELD_TYPE_INFO
                    ],
                    [
                        'name' => 'khách hàng',
                        'code' => 'customer',
                        'type' => Rikkei\Tag\View\TagConst::FIELD_TYPE_INFO
                    ],
                    [
                        'name' => 'số bug',
                        'code' => 'number_bug',
                        'type' => Rikkei\Tag\View\TagConst::FIELD_TYPE_INFO
                    ],
                    [
                        'name' => 'CSS',
                        'code' => 'css',
                        'type' => Rikkei\Tag\View\TagConst::FIELD_TYPE_INFO
                    ],
                ]
            ]
        ]
    ]
];
