<script>
var RKTagTrans = {
    'Field list': '{!! trans('tag::view.Field list') !!}',
    'Add': '{!! trans('tag::view.Add') !!}',
    'Edit': '{!! trans('tag::view.Edit') !!}',
    'Delete': '{!! trans('tag::view.Delete') !!}',
    'Up': '{!! trans('tag::view.Up') !!}',
    'Down': '{!! trans('tag::view.Down') !!}',
    'Create new field': '{!! trans('tag::view.Create new field') !!}',
    'Name': '{!! trans('tag::view.Name') !!}',
    'Status': '{!! trans('tag::view.Status') !!}',
    'Save': '{!! trans('tag::view.Save') !!}',
    'Close': '{!! trans('tag::view.Close') !!}',
    'Type': '{!! trans('tag::view.Type') !!}',
    'Parent': '{!! trans('tag::view.Parent') !!}',
    'Confirm': '{!! trans('tag::view.Confirm') !!}',
    'EConfirm': '{!! trans('tag::view.EConfirm') !!}',
    'Are you sure delete this field and all children?': '{!! trans('tag::view.Are you sure delete this field and all children?') !!}',
    'This field is required': '{!! trans('tag::view.This field is required') !!}',
    'Max length :number': '{!! trans('tag::view.Max length :number', ['number' => 255]) !!}',
    'Are you sure delete tag?': '{!! trans('tag::view.Are you sure delete tag?') !!}',
    'Approve': '{!! trans('tag::view.Approve') !!}',
    'Color': '{!! trans('tag::view.Color') !!}',
    'Basic info': '{!! trans('tag::view.Basic info') !!}',
    'Team allocation': '{!! trans('tag::view.Team allocation') !!}',
    'Add old project': '{!! trans('tag::view.Add old project') !!}',
    'PName': '{!! trans('tag::view.PName') !!}',
    'Alias': '{!! trans('tag::view.Alias') !!}',
    'Group': '{!! trans('tag::view.Group') !!}',
    'Group leader': '{!! trans('tag::view.Group leader') !!}',
    'Project Manager': '{!! trans('tag::view.Project Manager') !!}',
    'Level': '{!! trans('tag::view.Level') !!}',
    'PType': '{!! trans('tag::view.PType') !!}',
    'Status': '{!! trans('tag::view.Status') !!}',
    'Customer': '{!! trans('tag::view.Customer') !!}',
    'Salesperson': '{!! trans('tag::view.Salesperson') !!}',
    'Create Project': '{!! trans('tag::view.Create Project') !!}',
    'Billable Effort': '{!! trans('tag::view.Billable Effort') !!}',
    'Plan Effort': '{!! trans('tag::view.Plan Effort') !!}',
    'Start date': '{!! trans('tag::view.Start date') !!}',
    'End date': '{!! trans('tag::view.End date') !!}',
    'Programming language': '{!! trans('tag::view.Programming language') !!}',
    'Color': '{!! trans('tag::view.Color') !!}',
    'Show': '{!! trans('tag::view.Show') !!}',
    'Search': '{!! trans('tag::view.Search') !!}',
    'Team': '{!! trans('tag::view.Team') !!}',
    'Tags': '{!! trans('tag::view.Tags') !!}',
    'Not found item': '{!! trans('tag::message.Not found item') !!}',
    'Reset filter': '{!! trans('tag::view.Reset filter') !!}',
    'Total': '{!! trans('tag::view.Total') !!}',
    'entries': '{!! trans('tag::view.entries') !!}',
    'page': '{!! trans('tag::view.page') !!}',
    'Assignee': '{!! trans('tag::view.Assignee') !!}',
    'Edit tags': '{!! trans('tag::view.Edit tags') !!}',
    'Submit': '{!! trans('tag::view.Submit') !!}',
    'Edit assignee': '{!! trans('tag::view.Edit assignee') !!}',
    'Select assignee': '{!! trans('tag::view.Select assignee') !!}',
    'Please select assignee': '{!! trans('tag::message.Please select assignee') !!}',
    'No': '{!! trans('project::view.No') !!}',
    'Position': '{!! trans('project::view.Position') !!}',
    'Account': '{!! trans('project::view.Account') !!}',
    'PL': '{!! trans('project::view.PL') !!}',
    'Effort': '{!! trans('project::view.Effort') !!}',
    'Resource': '{!! trans('project::view.Resource') !!}',
    'Old project': '{!! trans('tag::view.Old project') !!}',
    'View detail': '{!! trans('project::view.View detail') !!}',
    'View detail on dashboard': '{!! trans('tag::view.View detail on dashboard') !!}',
    'View on dashboard': '{!! trans('tag::view.View on dashboard') !!}',
    'Edit tag for': '{!! trans("tag::view.Edit tag for") !!}',
    'Cancel': '{!! trans("tag::view.Cancel") !!}',
    'Confirm submit': '{!! trans('tag::message.Confirm submit') !!}',
    'Are you sure submit': '{!! trans('tag::message.Are you sure submit') !!}',
    'Confirm approve': '{!! trans("tag::message.Confirm approve") !!}',
    'Are you sure approve': '{!! trans("tag::message.Are you sure approve") !!}',
    'Are you sure action': '{!! trans("tag::message.Are you sure action") !!}',
    'Select teams': '{!! trans("tag::view.Select teams") !!}',
    'Next': '{!! trans("tag::view.Next") !!}',
    'Actual effort': '{!! trans("tag::view.Actual effort") !!}',
    'Prev': '{!! trans("tag::view.Prev") !!}',
    'Short name': '{!! trans("tag::view.Short name") !!}',
    'With the old project, you need to fill in some more information': 
        '{!! trans("tag::view.With the old project, you need to fill in some more information") !!}',
    'Old': '{!! trans("tag::view.Old") !!}',
    'Assign': '{!! trans("tag::view.Assign") !!}',
    'Project name': '{!! trans("tag::view.Project name") !!}',
    'Select action': '{!! trans("tag::view.Select action") !!}',
    'Email': '{!! trans("tag::view.Email") !!}',
    'Birthday': '{!! trans("tag::view.Birthday") !!}',
    'Gender': '{!! trans("tag::view.Gender") !!}',
    'Man month': '{!! trans("tag::view.Man month") !!}',
    'Time': '{!! trans("tag::view.Time") !!}',
    'Project type': '{!! trans("tag::view.Project type") !!}',
    'Sale': '{!! trans("tag::view.Sale") !!}',
    'Search email': '{!! trans("tag::view.Search email") !!}',
    'Basic info': '{!! trans("tag::view.Basic info") !!}',
    'Busy in next 3 months': '{!! trans("tag::view.Busy in next 3 months") !!}',
    'Description': '{!! trans("tag::view.Description") !!}',
    'Scope': '{!! trans("tag::view.Scope") !!}',
    'Not found tags': '{!! trans("tag::view.Not found tags") !!}',
    'Descriptions': '{!! trans("tag::view.Descriptions") !!}',
    'Customers provided': '{!! trans("tag::view.Customers provided") !!}',
    'Choose alias': '{!! trans("tag::view.Choose alias") !!}',
};
</script>
